runtime: python37
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app  --timeout 60
instance_class: F4
inbound_services:
- warmup
min_idle_instances: 1
vpc_access_connector:
  name: projects/foodie-recommender-api/locations/europe-central2/connectors/connector-rec-system
  egress_setting: all-traffic