runtime: python37
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app  --timeout 60
instance_class: F2
vpc_access_connector:
name: projects/foodie-recommender-api/locations/europe-central2/connectors/connector-rec-system
egress_setting: all-traffic