create table ingredients (id bigint not null auto_increment, amount double precision, name varchar(255), unit varchar(255), recipe_id bigint, primary key (id)) engine=InnoDB;
create table post_comments (id bigint not null auto_increment, content varchar(255), created_at datetime, post_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table post_likes (id bigint not null auto_increment, created_at datetime, post_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table posts (id bigint not null auto_increment, description varchar(255), image_path varchar(255), created_at datetime, title varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table recipe_comments (id bigint not null auto_increment, content varchar(255), created_at datetime, recipe_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table recipe_likes (id bigint not null auto_increment, created_at datetime, recipe_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table recipes (id bigint not null auto_increment, bitterness float, calories integer, carbs integer, dairy_free bit, fat integer, fattiness float, gluten_free bit, image varchar(255), instructions varchar(255), protein integer, ready_in_minutes integer, saltiness float, servings integer, sourness float, spiciness float, sweetness float, created_at datetime, title varchar(255), vegan bit, vegetarian bit, verified bit, very_healthy bit, user_id bigint, primary key (id)) engine=InnoDB;
create table recipes_for_days (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table recipes_for_days_recipes (recipes_for_days_id bigint not null, recipesOneDay_id bigint not null) engine=InnoDB;
create table recipes_for_weeks (id bigint not null auto_increment, user_id bigint, primary key (id)) engine=InnoDB;
create table recipes_for_weeks_recipes_for_days (recipes_for_weeks_id bigint not null, weekRecipesList_id bigint not null) engine=InnoDB;
create table surveys (id bigint not null auto_increment, answer1 integer, answer10 integer, answer11 integer, answer12 integer, answer13 integer, answer2 integer, answer3 integer, answer4 integer, answer5 integer, answer6 integer, answer7 integer, answer8 integer, answer9 integer, exclusions varchar(255), created_at datetime, user_id bigint, primary key (id)) engine=InnoDB;
create table user_socials (id bigint not null auto_increment, discord varchar(255), facebook varchar(255), instagram varchar(255), telegram varchar(255), twitter varchar(255), youtube varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table user_stats (id bigint not null auto_increment, age integer, bmi double precision, cal integer, gender integer, height integer, updated_at datetime, weight double precision, user_id bigint not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, authority varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), login_password varchar(255), created_at datetime, primary key (id)) engine=InnoDB;
alter table recipes_for_days_recipes add constraint UK_qya8uvfesk6ky8l11fpgfqsnp unique (recipesOneDay_id);
alter table recipes_for_weeks_recipes_for_days add constraint UK_s8wikuosfmamdct4tyqg2lksf unique (weekRecipesList_id);
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes (id);
alter table post_comments add constraint FKaawaqxjs3br8dw5v90w7uu514 foreign key (post_id) references posts (id);
alter table post_comments add constraint FKrn27ncjs8y0upol448yposgjb foreign key (creator_id) references users (id);
alter table post_likes add constraint FKa5wxsgl4doibhbed9gm7ikie2 foreign key (post_id) references posts (id);
alter table post_likes add constraint FKtbt8vui6rshejs7b27d9uh08x foreign key (creator_id) references users (id);
alter table posts add constraint FKpbdq30fxpf8l0v3j2eyca7odb foreign key (creator_id) references users (id);
alter table recipe_comments add constraint FKiaxbdm0pmos17k3tp7f4fuugd foreign key (recipe_id) references recipes (id);
alter table recipe_comments add constraint FK5nv3a7m6bnb1q54ulapl8w5mp foreign key (creator_id) references users (id);
alter table recipe_likes add constraint FK123rwitbkijue4y39x2a9pqqb foreign key (recipe_id) references recipes (id);
alter table recipe_likes add constraint FK5tjpee1krp7dmtp15b2co4vy5 foreign key (creator_id) references users (id);
alter table recipes add constraint FKlc3x6yty3xsupx80hqbj9ayos foreign key (user_id) references users (id);
alter table recipes_for_days_recipes add constraint FKpnbatl3bb3osb4u3l8w9d4lxt foreign key (recipesOneDay_id) references recipes (id);
alter table recipes_for_days_recipes add constraint FKculoe30fgeowx33calc546uy foreign key (recipes_for_days_id) references recipes_for_days (id);
alter table recipes_for_weeks add constraint FKk6tfqmfjd0155dnypj99o37ss foreign key (user_id) references users (id);
alter table recipes_for_weeks_recipes_for_days add constraint FKnv82xf2mcyur44nq42sq7h0dm foreign key (weekRecipesList_id) references recipes_for_days (id);
alter table recipes_for_weeks_recipes_for_days add constraint FKth00pmwretgrvurlig3vbh167 foreign key (recipes_for_weeks_id) references recipes_for_weeks (id);
alter table surveys add constraint FKiydpdbdg90l5bl365gt67qgrn foreign key (user_id) references users (id);
alter table user_socials add constraint FKg9g1d5p5054bobredv47pqbg5 foreign key (user_id) references users (id);
alter table user_stats add constraint FKj277c5rcqlsvwkk3hj39e2b74 foreign key (user_id) references users (id);
