create table excluded_products (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=InnoDB;
create table excluded_products_products (excluded_products_id bigint not null, listOfExcludedProducts_id bigint not null) engine=InnoDB;
create table following (id bigint not null auto_increment, follower_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table ingredients (id bigint not null auto_increment, amount double precision, name varchar(255), unit varchar(255), recipe_id bigint, primary key (id)) engine=InnoDB;
create table post_comments (id bigint not null auto_increment, content varchar(255), created_at datetime, post_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table post_likes (id bigint not null auto_increment, created_at datetime, post_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table posts (id bigint not null auto_increment, description varchar(255), image_path varchar(255), created_at datetime, title varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table products (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table ratings (id bigint not null auto_increment, score integer, recipe_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table recipe_comments (id bigint not null auto_increment, content varchar(255), created_at datetime, recipe_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table recipe_likes (id bigint not null auto_increment, created_at datetime, recipe_id bigint, creator_id bigint, primary key (id)) engine=InnoDB;
create table recipes (id bigint not null auto_increment, bitterness float, calories integer, carbs integer, dairy_free bit, fat integer, fattiness float, gluten_free bit, image varchar(255), instructions varchar(255), protein integer, ready_in_minutes integer, saltiness float, servings integer, sourness float, spiciness float, sweetness float, created_at datetime, title varchar(255), vegan bit, vegetarian bit, verified bit, very_healthy bit, user_id bigint, primary key (id)) engine=InnoDB;
create table recipes_for_day (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table recipes_for_day_recipes (recipes_for_day_id bigint not null, recipesForToday_id bigint not null) engine=InnoDB;
create table recipes_for_day_recipes_for_week (recipes_for_day_id bigint not null, dietWeek_id bigint not null) engine=InnoDB;
create table recipes_for_week (id bigint not null auto_increment, goal integer, start_weight double precision, timestamp datetime, user_id bigint, primary key (id)) engine=InnoDB;
create table recipes_for_week_recipes_for_day (recipes_for_week_id bigint not null, daysForWeekDiet_id bigint not null) engine=InnoDB;
create table subscriptions (id bigint not null auto_increment, final_payment_time datetime, payer_id varchar(255), start_time datetime, status varchar(255), subscription_id varchar(255), valid_till datetime, user_id bigint, primary key (id)) engine=InnoDB;
create table surveys (id bigint not null auto_increment, answer1 integer, answer10 integer, answer11 integer, answer12 integer, answer13 integer, answer2 integer, answer3 integer, answer4 integer, answer5 integer, answer6 integer, answer7 integer, answer8 integer, answer9 integer, created_at datetime, user_id bigint, primary key (id)) engine=InnoDB;
create table user_extras (id bigint not null auto_increment, about_me varchar(255), background_image varchar(255), discord varchar(255), facebook varchar(255), instagram varchar(255), profession varchar(255), telegram varchar(255), twitter varchar(255), youtube varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table user_stats (id bigint not null auto_increment, age integer, bmi double precision, cal integer, gender integer, height integer, updated_at datetime, weight double precision, user_id bigint not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, authority varchar(255), email varchar(255), first_name varchar(255), image_path varchar(255), last_name varchar(255), login_password varchar(255), rating bit, subscribed bit, survey bit, created_at datetime, primary key (id)) engine=InnoDB;
alter table excluded_products_products add constraint UK_aq179or6l2h8ftj9iuxqqbj7l unique (listOfExcludedProducts_id);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table excluded_products add constraint FKgb1js7uidnmviora0jp3ddhuv foreign key (user_id) references users (id);
alter table excluded_products_products add constraint FKq65nw6nlnle0a8u6sodpm3lw9 foreign key (listOfExcludedProducts_id) references products (id);
alter table excluded_products_products add constraint FK69wlyt97635thbcn01vlfmka6 foreign key (excluded_products_id) references excluded_products (id);
alter table following add constraint FK7o8rmeuf83dqi0b2bvdhuwo9g foreign key (follower_id) references users (id);
alter table following add constraint FKs8v9phajoli0ka1vbrj7ypkpd foreign key (user_id) references users (id);
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes (id);
alter table post_comments add constraint FKaawaqxjs3br8dw5v90w7uu514 foreign key (post_id) references posts (id);
alter table post_comments add constraint FKrn27ncjs8y0upol448yposgjb foreign key (creator_id) references users (id);
alter table post_likes add constraint FKa5wxsgl4doibhbed9gm7ikie2 foreign key (post_id) references posts (id);
alter table post_likes add constraint FKtbt8vui6rshejs7b27d9uh08x foreign key (creator_id) references users (id);
alter table posts add constraint FKpbdq30fxpf8l0v3j2eyca7odb foreign key (creator_id) references users (id);
alter table ratings add constraint FK12o4ql2wkhay4u9qw2ashmho7 foreign key (recipe_id) references recipes (id);
alter table ratings add constraint FKb3354ee2xxvdrbyq9f42jdayd foreign key (user_id) references users (id);
alter table recipe_comments add constraint FKiaxbdm0pmos17k3tp7f4fuugd foreign key (recipe_id) references recipes (id);
alter table recipe_comments add constraint FK5nv3a7m6bnb1q54ulapl8w5mp foreign key (creator_id) references users (id);
alter table recipe_likes add constraint FK123rwitbkijue4y39x2a9pqqb foreign key (recipe_id) references recipes (id);
alter table recipe_likes add constraint FK5tjpee1krp7dmtp15b2co4vy5 foreign key (creator_id) references users (id);
alter table recipes add constraint FKlc3x6yty3xsupx80hqbj9ayos foreign key (user_id) references users (id);
alter table recipes_for_day_recipes add constraint FKl7re3dhk2bs7mv2012qrglg9u foreign key (recipesForToday_id) references recipes (id);
alter table recipes_for_day_recipes add constraint FKl4kqk5p63c9j5pt2rtgyepwmu foreign key (recipes_for_day_id) references recipes_for_day (id);
alter table recipes_for_day_recipes_for_week add constraint FK9w6knf7mnq3asrdo8y5vbljhq foreign key (dietWeek_id) references recipes_for_week (id);
alter table recipes_for_day_recipes_for_week add constraint FKo3s4555vqc1oc01yyrq57lr9k foreign key (recipes_for_day_id) references recipes_for_day (id);
alter table recipes_for_week add constraint FKtosnicydc3rhvvnpccxts4mq4 foreign key (user_id) references users (id);
alter table recipes_for_week_recipes_for_day add constraint FK6fmmylkfdol0cnfcs2724yp6b foreign key (daysForWeekDiet_id) references recipes_for_day (id);
alter table recipes_for_week_recipes_for_day add constraint FKootxeyl92toyw4ig7dg003wvl foreign key (recipes_for_week_id) references recipes_for_week (id);
alter table subscriptions add constraint FKhro52ohfqfbay9774bev0qinr foreign key (user_id) references users (id);
alter table surveys add constraint FKiydpdbdg90l5bl365gt67qgrn foreign key (user_id) references users (id);
alter table user_extras add constraint FKryu4ecjpgfb9hjauu1d4954ah foreign key (creator_id) references users (id);
alter table user_stats add constraint FKj277c5rcqlsvwkk3hj39e2b74 foreign key (user_id) references users (id);
